### ISSUE TITLE
Testing puppet

### ISSUE THREAD

**Issue by yarmand** [rubyhacknight/meetups#10]
I'd like to experiment around testing Puppet recipes and be able to write them using TDD.
2 tools I'd like to give a try are:
- https://github.com/puppetlabs/beaker
- http://rspec-puppet.com/

**Comment by sideshowcoder** [comment]
I'm in!

**Comment by sideshowcoder** [comment]
WE DID IT https://github.com/sideshowcoder/rubyhacknight-testing-puppet!!!!! thanks Dmitry and Yann
