### ISSUE TITLE
Code Kata - Anagrams

### ISSUE THREAD

**Issue by sideshowcoder** [rubyhacknight/meetups#12]
http://codekata.com/kata/kata06-anagrams/ 

Try to find anagrams for words, this can be really interesting in terms of how to write working code first and then optimize.

**Comment by lpil** [comment]
Certainly not the prettiest bit of code in the world, but it sorta works. I skipped over words that were invalid utf-8 as I wasn't sure what we were supposed to do with them.

``` ruby
words = File.readlines('wordlist.txt')
groups = {}

words.each do |word|
  word = word.chomp
  begin
    key = word.downcase.split('').sort.join('')
    groups[key] = groups.fetch(key, []) << word
  rescue
    nil
  end
end

File.open('out.txt', 'w') do |f|
  groups.values.each do |e| 
    f.puts e.join(' ')
  end
end
```

Takes 5 seconds on my machine. Would like to see how the author got to 1.8 seconds!

**Comment by sideshowcoder** [comment]
Very cool :), could it be that he split the file into sections and processed it on different processes? Doing a read + seek to jump to the sections on read.

**Comment by lpil** [comment]
Using threads with Ruby? Is that allowed? ;)

**Comment by sideshowcoder** [comment]
nooo are you crazy? Processes is where it's at! :dancer:

**Comment by neudabei** [comment]
Nice solution, Ipil!

I took a different approach to the problem and came up with this:

``` ruby
class Anagram

  def initialize(word)
    @word = word
  end

  def create_new_words
    @array_of_word_versions = @word.downcase.chars.permutation.to_a # [["h", "i"], ["i", "h"]]
    @array_of_word_versions_joined = []
    @array_of_word_versions.each do |word|
      @array_of_word_versions_joined << word.join
    end
  end

  def check_word_exists
    @dictionary = File.readlines("wordlist.txt")
    @valid_word_array = []
      @array_of_word_versions_joined.each do |word|
        if @dictionary.include?("#{word}\n")
          @valid_word_array << word
        end
      end
    @valid_word_array.delete(@word.downcase)
    if @valid_word_array.empty? 
      puts "No anagrams could be formed out of '#{@word}'"
    else
      puts "'#{@word}' can be turned into the following anagrams: #{@valid_word_array}" 
    end
  end

end

anagram = Anagram.new("More")
anagram.create_new_words
anagram.check_word_exists
```

Instead of using the words in the dictionary you can pass in any word and check if a different combination of the letters in the word exists in the dictionary. If it does it qualifies as an Anagram. This is painfully slow when words are longer than 5 letters. 

Thanks for the Hacknight yesterday. It was fun!
