### ISSUE TITLE
RSpec presentation

### ISSUE THREAD

**Issue by Saphyel** [rubyhacknight/meetups#16]
Hello, I was wondering if someone could make a presentation of Rspec, I would appreciate it because I'm learning it and any help is welcome! :)

**Comment by sideshowcoder** [comment]
@yarmand that is one for you maybe I hear you are a fan :dancer:

**Comment by yarmand** [comment]
Sorry @Saphyel I'm really late to answer on this one. I guess in the meantime you advance a lot on the subject. If you still want to talk about RSpec or explore some more advance usage of it, I'd be happy to chat on next meetup.
