### ISSUE TITLE
Can we add the slides from the Rack and Grape meets?

### ISSUE THREAD

**Issue by lpil** [rubyhacknight/meetups#4]
:)

**Comment by sideshowcoder** [comment]
:+1: I'll add the rack slides @nickcampbell18 could you add the grape ones?

**Comment by sideshowcoder** [comment]
rack slides are in `2015/february/rack-hack` together with the code.

**Comment by sideshowcoder** [comment]
@lpil https://github.com/rubyhacknight/meetups/blob/master/2015/march/future-proof-apis.md :+1:

**Comment by lpil** [comment]
<3
